### PR TITLE
Coverage for unmatched open bracket

### PR DESCRIPTION
**Pull request by dmateusp**
@barrywhart can you have a look? I'm not too familiar with the coverage stuff, I ran the report locally but I'm not sure how to get a diff

### CODE REVIEW

**Comment by barrywhart** [comment]
In this case, since we're interested in the coverage of one particular line, I just set a breakpoint on that line. The new test doesn't hit it. It's hitting another error case on line 584. (Note the differing `SQLParseError` error messages.)
```
580  	                        else:
581  	                            # No we can't. We don't have a match and we're in a bracket stack.
582  	                            import pdb; pdb.set_trace()
583  ->	                            raise SQLParseError(
584  	                                "Couldn't find closing bracket for opening bracket.",
585  	                                segment=bracket_stack[-1].bracket,
586  	                            )
587  	                        # We have attempted a potential solution to the problem. Loop around.
588  	                        continue
```

**Comment by dmateusp** [comment]
oops! ok let me give it another try

**Comment by dmateusp** [comment]
This time it should work @barrywhart 331 misses to 330

**Comment by barrywhart** [comment]
Strange -- it looks like we're still hitting a different area of the code -- around line 630 rather than line 560. The error message is the same (or similar), though:
```
629  	                            if bracket_is_definite:
630  	                                # We've found an unexpected end bracket!
631  	                                import pdb; pdb.set_trace()
632  ->	                                raise SQLParseError(
633  	                                    f"Found unexpected end bracket!, was expecting one of: {matchers + bracket_matchers}, but got {matcher}",
634  	                                    segment=match.matched_segments[0],
635  	                                )
```

I'll take a look as well, to see if I can find a way to test it (possibly today, possibly later).

**Comment by barrywhart** [comment]
I read through the code carefully. In order to hit it, we'd have to encounter the following conditions:
* Bracket stack not empty.
* Everything on the stack is definite.
* Found an end bracket.
* Types don't match
* End is definite

I found a case that does this -- a slight variant on your test. Thanks for getting me unstuck on this! 💪🏽 I will merge your PR into mine, then update your test with my findings.

**Comment by dmateusp** [comment]
Thanks! I'll have a look at your test case I'm very curious

**Pull request merged**
